backend:
  name: git-gateway
  branch: main

# when using the default proxy server port
local_backend: true

site_url: ""
display_url: ""
logo_url: ""

media_folder: "uploads"

collections:
  - label: "Site Settings" # site settings
    name: "site_settings"
    editor:
      preview: false
    delete: true
    files:
      - label: "Landing Page"
        name: "landing_page"
        file: "_data/landing.yml"
        fields:
          - label: "Gradient Title"
            name: "landingTitleGradient"
            widget: "string"
            required: true
            hint: "Ex. Meliora"
          - label: "Tagline"
            name: "landingTagline"
            widget: "string"
            required: true
            hint: "Ex. The evolving chronicles"
          - label: "Description"
            name: "landingDescription"
            widget: "text"
            required: false
            hint: "This keywords will be appeared on search engines."
  - label: "Magazine" # magazine field
    name: "magazine"
    folder: "_magazine"
    create: true
    identifier_field: "title"
    slug: "{{year}}-{{month}}-{{day}}_{{slug}}"
    editor:
      preview: false
    fields:
      - label: "Published Date" # date of publish of magazine
        name: "date" 
        widget: "datetime"
        date_format: "DD.MM.YYYY"
        time_format: "HH:mm"
        picker_utc: true # UTC time picker
        required: true
      - label: "Title of Magazine" # title of magazine
        name: "title"
        widget: "string"
        required: true
        hint: "Ex: Meliora'1"
      - label: "Featured image" # featured image of magazine
        name: "featured_image"
        widget: "image"
        media_folder: /uploads/featured_images
        allow_multiple: false
        required: true
      - label: "Cover photo by" # cover photo author
        name: "cover_author"
        widget: "string"
        required: true
        hint: "Eg: John Doe"
      - label: "Upload the magazine" # magazine file
        name: "magazine_file"
        widget: "file"
        media_folder: /uploads/magazine_files
        allow_multiple: false
        required: true
      - label: "Features" # magazine feature
        name: "feature"
        widget: "object"
        collapsed: true
        summary: "{{fields.title}}: {{ fields.page_No}}"
        fields:
          - label: "Title"
            name: "title"
            widget: "string"
            required: true
            hint: "Eg: G-toons"
          - label: "Page No"
            name: "page_No"
            widget: "string"
            required: true
            hint: "Eg: 3-4"
      - label: "Team Members" # magazine team
        name: "team"
        widget: "object"
        collapsed: true
        summary: "{{fields.name}}"
        fields:
          - label: "Name"
            name: "name"
            widget: "string"
            required: true
            hint: "Eg: John Doe"
          - label: "Profile Photo"
            name: "photo"
            widget: "image"
            media_folder: /uploads/team_profile
            allow_multiple: false
            required: true