backend:
  name: git-gateway
  branch: main

# when using the default proxy server port
local_backend: true

# Editorial workflow
publish_mode: editorial_workflow

site_url: ""
display_url: ""
logo_url: ""

media_folder: "uploads"

collections:
  - label: "Site Settings" # site settings
    name: "site_settings"
    editor:
      preview: false
    delete: true
    files:
      - label: "Metadata"
        name: "metadata"
        file: "_data/metadata.yml"
        fields:
          - label: "Title"
            name: "title"
            widget: "string"
            required: true
            hint: "Ex. Meliora"
          - label: "Email"
            name: "email"
            widget: "string"
            required: true
            hint: "Ex. someone@doamin.com"
          - label: "Description"
            name: "description"
            widget: "text"
            required: true
            hint: "This keywords will be appeared on search engines."
          - label: "Site's URL"
            name: "url"
            widget: "string"
            required: true
            hint: "Ex. something.com / something.domain.com"
          - label: "Author of website"
            name: "author"
            widget: "string"
            required: true
            hint: "Ex. John Doe"
      - label: "Landing Page"
        name: "landing_page"
        file: "_data/landing.yml"
        fields:
          - label: "Gradient Title"
            name: "landingTitleGradient"
            widget: "string"
            required: true
            hint: "Ex. Meliora"
          - label: "Tagline"
            name: "landingTagline"
            widget: "string"
            required: true
            hint: "Ex. The evolving chronicles"
          - label: "Description"
            name: "landingDescription"
            widget: "text"
            required: false
            hint: "This keywords will be appeared on search engines."
  - label: "Magazine" # magazine field
    name: "magazine"
    folder: "_magazine"
    create: true
    identifier_field: "title"
    slug: "{{year}}-{{month}}-{{day}}_{{slug}}"
    editor:
      preview: false
    fields:
      - label: "Published Date" # date of publish of magazine
        name: "date" 
        widget: "datetime"
        date_format: "DD.MM.YYYY"
        time_format: "HH:mm"
        picker_utc: true # UTC time picker
      - label: "Do you want to set this release as coming soon?"
        name: "comingSoon"
        widget: "boolean"
        default: false
        hint: "If this is a release please choose false."
      - label: "Text color"
        name: "text_color"
        widget: "color"
      - label: "Title of Magazine" # title of magazine
        name: "title"
        widget: "string"
        hint: "Ex: Meliora'1"
      - label: "Featured image" # featured image of magazine
        name: "featured_image"
        widget: "image"
        media_folder: /uploads/featured_images
        allow_multiple: false
        required: true
      - label: "Cover Photo Author" # Cover Photo Author
        name: "cover"
        widget: "object"
        collapsed: false
        summary: "{{fields.name}}"
        fields:
          - label: "Name"
            name: "name"
            widget: "string"
            hint: "Eg: John Doe"
          - label: "Photo"
            name: "photo"
            widget: "image"
            media_folder: /uploads/cover_authors
            allow_multiple: false
      - label: "Editor's Area" # editors area
        name: "editor"
        widget: "object"
        collapsed: false
        summary: "{{fields.name}}"
        fields:
          - label: "Name"
            name: "name"
            widget: "string"
            hint: "Eg: John Doe"
          - label: "Editor's Note"
            name: "note"
            widget: "text"
      - label: "Features description" # title of magazine
        name: "features_description"
        widget: "text"
      - label: "Features" # magazine feature
        name: "feature"
        widget: "list"
        allow_add: true
        collapsed: true
        summary: "{{fields.title}}: {{ fields.page_No}}"
        fields:
          - label: "Title"
            name: "title"
            widget: "string"
            hint: "Eg: G-toons"
          - label: "Page No"
            name: "page_No"
            widget: "string"
            hint: "Eg: 3-4"
      - label: "Team description" # title of magazine
        name: "team_description"
        widget: "text"
      - label: "Team Members" # magazine team
        name: "team"
        widget: "list"
        collapsed: true
        allow_add: true
        summary: "{{fields.name}}"
        fields:
          - label: "Name"
            name: "name"
            widget: "string"
            hint: "Eg: John Doe"
          - label: "Profile Photo"
            name: "photo"
            widget: "image"
            media_folder: /uploads/team_profile
            allow_multiple: false
      - label: "Upload the magazine" # magazine file
        name: "magazine_file"
        widget: "file"
        media_folder: /uploads/magazine_files
        allow_multiple: false